### ISSUE TITLE
Building Tools

### ISSUE THREAD

**Issue by ManyBabySpooderMans** [spaar/besiege-modloader#63]
My building tools do not work. Every step was followed EXACTLY. We tried everything, but the icon for the mod never shows up. Help would be appreciated. It's maddening.

**Comment by spaar** [comment]
I'm assuming you tried to do this with the new Multiverse update? The mod loader does not support that yet, it could be a while before proper support lands.

**Comment by ManyBabySpooderMans** [comment]
Well, I tried to do it on sandbox. Approximate date that it WILL work? Also, does the new version of the building tools work for multiverse and all? Cause, I don't do that much multiverse, even though the feature is great.

**Comment by ManyBabySpooderMans** [comment]
Also, even if everything was installed correctly, will it not work?

**Comment by ManyBabySpooderMans** [comment]
And, will we have to reinstall when it is supported?

**Comment by ManyBabySpooderMans** [comment]
Excuse me?

**Comment by ManyBabySpooderMans** [comment]
? Why the emojis?

**Comment by spaar** [comment]
Sorry for the delayed response.
The mod loader does not currently work on the multiverse update at all, not even if you don't use the MP features. This is because the update changed the internal structure of the game quite significantly and so it will take some time to update it. I'm afraid I can't really say how long it's going to take at the moment.

If you still want to build machines using mods in the meantime, it's possible to download the older version using the "previousbuild" beta branch on Steam. You can still install the mod loader on top of that. It is even possible to have the old version with mods and the Multiverse version without mods installed side-by-side so you can easily switch back and forth.

**Comment by spaar** [comment]
See #65 for more information.
